### ISSUE TITLE
Document node API

### ISSUE THREAD

**Issue by cowwoc** [mdreizin/gulp-webpack-build#1]
Please document `webpack.failAfter()` and other API methods. The example provided in README.md is a good start, but it's not clear what functions exist, what configuration options they take, and what each one does.

**Comment by cowwoc** [comment]
Looks good, thanks!

One last question: Are `webpack.core` and `webpack.config` meant to be read-only properties? Or are you meant to be able to set them after constructing an instance, before running `compile()`?

**Comment by mdreizin** [comment]
@cowwoc They are read-only.
