### ISSUE TITLE
gulp.dest() not relative to output.path

### ISSUE THREAD

**Issue by nub4life** [mdreizin/gulp-webpack-build#10]
If, in webpack.config.js, I have:
```javascript
    output: {
        path: path.resolve(__dirname, './test')
    }
```
And in my gulpfile.js, I have gulp.dest('js'), the outputted files get put into js/test. According to the documentation, "gulp.dest can be used. gulp.dest is resolved relative to output.path if it is set". That to me sounds like the files should get put into test/js. Am I doing something wrong or am I misunderstanding the documentation?

**Comment by mdreizin** [comment]
@nub4life Could you please provide working example?

**Comment by nub4life** [comment]
Task in gulpfile.js, where $g.webpackBuild is loaded via gulp-load-plugins:

```javascript
gulp.task('webpack', function() {
    return gulp.src('./webpack.config.js')
        .pipe($g.webpackBuild.compile({
            useMemoryFs: true
        }))
        .pipe($g.webpackBuild.format(
        {
            verbose: verbose
        }))
        .pipe($g.webpackBuild.failAfter({
            errors: true,
            warnings: true
        }))
        .pipe(gulp.dest('js'));
});
```

In webpack.config.js, output prop:
```javascript
output: {
		path: path.resolve(__dirname, './test'),
		filename: '[name].js',
		libraryTarget: 'var'
	}
```

**Comment by mdreizin** [comment]
@nub4life I have just added test for this case. Please look at [test/fixtures/output-path-custom/webpack.config.js](https://github.com/mdreizin/gulp-webpack-build/blob/master/test/fixtures/output-path-custom/webpack.config.js).

**Comment by jacek-dargiel** [comment]
sorry to hop in on an issue, but i have a related problem. I think my files are outputed by both webpack and gulp. The result is that i have files in both my gulp output directory, and my CWD.

My webpack.config.js:
```javascript
var path = require('path');
var webpack = require('webpack');
module.exports = {
	entry: './js/main.js',
	output: {
		path: './',
		filename: 'codebase.js'
	},
	resolve: {
		root: [path.join(__dirname, 'bower_components')]
	},
	plugins: [
		new webpack.ResolverPlugin(
			new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
		)
	],
	devtool: '#source-map',
};
```

and my gulp task:
```javascript
var CONFIG = {
	paths: {
		output: {
			scripts: 'build/js',
		}
	},
	webpack:{
		webpackConfig: webpack.config.CONFIG_FILENAME
	}
};
gulp.task('scripts', ['scripts:lint'], function () {
	return gulp
			.src(CONFIG.webpack.webpackConfig)
			
			.pipe(webpack.configure({}))
			.pipe(webpack.compile())

			.pipe(gulp.dest(CONFIG.paths.output.scripts));
});
```

**Comment by mdreizin** [comment]
@jacek-dargiel Please set `useMemoryFs` to `true` to preventing creation files by `webpack`. For more details please see [API doc](https://github.com/mdreizin/gulp-webpack-build/blob/master/docs/API.md#module_gulp-webpack-build.configure).
