### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by cliren** [mdreizin/gulp-webpack-build#12]
Using: "gulp-webpack-build": "^0.5.1"

I get the below error when using UglifyJsPlugin. Native webpack builds fine with the same configuration. gulp-webpack-build works fine when I remove the uglify plugin.

plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin()
  ]

events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (/Users/jsder/dev/lib1/node_modules/gulp-webpack-build/index.js:253:23)
    at DestroyableTransform.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:163:7)
    at /Users/jsder/dev/lib1/node_modules/gulp-webpack-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickDomainCallback (node.js:363:11)

**Comment by mdreizin** [comment]
@cliren I'm sorry for late response. Could you please share your `webpack.config.js` and `gulp` tasks to figure out what is wrong?

**Comment by cliren** [comment]
@mdreizin https://github.com/cliren/test-gulp-webpack-build. I have setup a example project to reproduce the error.

**Comment by mdreizin** [comment]
@cliren Thanks a lot!

I have run command ```gulp``` and I have got:

```
WARNING in main.js from UglifyJs
Condition always false [./~/style-loader!./~/css-loader!./~/less-loader!./src/main.less:9,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/less-loader!./src/main.less:11,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/less-loader!./src/main.less:7,0]
Condition always false [./~/style-loader/addStyles.js:23,0]
Dropping unreachable code [./~/style-loader/addStyles.js:24,0]
```

then ```webpack --config webpack.config.js``` and got the same result:

```

WARNING in main.js from UglifyJs
Condition always false [./~/style-loader!./~/css-loader!./~/less-loader!./src/main.less:9,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/less-loader!./src/main.less:11,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/less-loader!./src/main.less:7,0]
Condition always false [./~/style-loader/addStyles.js:23,0]
Dropping unreachable code [./~/style-loader/addStyles.js:24,0]
```

If you would like to suppress warnings please use:

```
gulpWebpack.failAfter({
      errors: true,
      warnings: false // it helps to suppress warnings
    })
```

in this case `gulp-webpack-build` will not fail the build.

**Comment by cliren** [comment]
great, thanks!

**Comment by mdreizin** [comment]
@cliren Can I close this issue now?

**Comment by cliren** [comment]
Sorry forgot to do that.
