### ISSUE TITLE
Watch compiles only first time

### ISSUE THREAD

**Issue by jacek-dargiel** [mdreizin/gulp-webpack-build#13]
I have an issue with `watch`. The first time i change a file webpack emits the compiled files, but next time i change them nothing hapens. The callback is not called. It's as if `webpack.watch` only runs the compilation, but doesn't watch the files any more.

Here is my configuration:
https://gist.github.com/jacek-dargiel/59a559c1fb6888727659

What am I doing wrong?

**Comment by mdreizin** [comment]
@jacek-dargiel Please use `gulp.watch` instead of `gulp-watch`.

**Comment by jacek-dargiel** [comment]
Replacing `gulp-watch` with the standard `gulp.watch` doesn't help. I don't think that's the source of the problem. `gulp-watch` detects the first change, and detects the subsequent changes, it's `webpack.watch` that doesn't fire its callback.

**Comment by mdreizin** [comment]
@jacek-dargiel I have tested with `gulp-watch` and it didn't work correctly, but it works fine with `gulp.watch`.

It is very difficult to reproduce your issue without working example. Could you please fork the repo and create an example under `test/fixtures` which reproduces your issue.

**Comment by jacek-dargiel** [comment]
Sorry, it's taking longer than I thought, because I have python 3.3

**Comment by jacek-dargiel** [comment]
Ok, here's my fork with the fixture:
https://github.com/jacek-dargiel/gulp-webpack-build/tree/master/test/fixtures/watch-once

Now, I have dug deeper into the problem, and noticed that I was requiring a file with a different case filename - `require('./module1.js')`, while the actual file was `Module1.js`. I would expect webpack to throw some kind of error that it can't find `./module1.js`, but instead it uses `Module1.js` in the first build, and then ignores subsequent changes to that file.

BTW, I'm running Windows 8.1 - that may make a difference, as windows file names are case insensitive AFAIR.

Do you want a PR with this fixture?

**Comment by jacek-dargiel** [comment]
Closing this, as this is an issue with webpack, not the gulp plugin. https://github.com/webpack/webpack/issues/944
