### ISSUE TITLE
webpack should be a peerDependency

### ISSUE THREAD

**Issue by peleteiro** [mdreizin/gulp-webpack-build#16]
The DedupePlugin crashs if two webpack are loaded. And it makes sense making it a peerDependecy.
(It should be a peerDependency at webpack-config as well)

```
./node_modules/gulp-webpack-build/node_modules/webpack/lib/NormalModule.js:116
		if(!template) throw new Error("No template for dependency: " + dep.Class.nam
```

The workaround is running npm dedupe before using gulp-webpack-build.

**Comment by mdreizin** [comment]
@peleteiro As I understand it would be:

```
"dependencies": {
    "webpack": "^1.9.4",
    "webpack-config": "^0.7.0"
  },
  "peerDependencies": {
    "webpack": "^1.9.4",
    "webpack-config": "^0.7.0"
  }
```

**Comment by mdreizin** [comment]
@peleteiro please update to v0.11.1 and let me know if it helps you.

**Comment by peleteiro** [comment]
Sorry, my mistake. webpack-config should be at dependencies.

**Comment by mdreizin** [comment]
@peleteiro have you got any errors using the latest version? I'm going to close this issue if everything is ok.

**Comment by jgerigmeyer** [comment]
I don't understand why ``webpack-config`` is listed under ``peerDependencies``. It works fine if it's just installed as a dependency, and listing it as a peer-dependency causes unnecessary warnings in npm 2.x.

**Comment by mdreizin** [comment]
@jgerigmeyer could you please shared your `package.json` and `npm install` log with warning.

**Comment by jgerigmeyer** [comment]
```json
{
  "devDependencies": {
    "gulp": "3.9.0",
    "gulp-webpack-build": "0.13.1"
  },
  "dependencies": {
    "webpack": "1.12.2"
  }
}
```

```bash
$ npm install
npm WARN peerDependencies The peer dependency webpack-config@^0.8.0 included from gulp-webpack-build will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

Obviously the warning goes away if I add ``webpack-config`` as a dev dependency; I'm just not sure why I should need to do that since ``gulp-webpack-build`` installs it as a dependency anyway.
