### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by cowwoc** [mdreizin/gulp-webpack-build#2]
If I run `webpack` or `gulp-webpack` from gulp, I get output from webpack. If I run `gulp-webpack-build` I get no output. No error messages, no warnings, no success messages. Nothing. I also don't see any files being written to disk.

My code looks like this:

```
var webpack = require("gulp-webpack-build");
gulp.task("package", function()
{
	return gulp.src(config.srcDir + "**/*.js").
		pipe(webpack.compile()).
		pipe(webpack.format(
		{
			version: false,
			timings: true
		})).
		pipe(webpack.failAfter(
		{
			errors: true,
			warnings: true
		})).
		pipe(gulp.dest(config.targetDir)).
		pipe(reload({stream: true}));
});
```

I am running node v0.10.35, npm 1.4.28, Windows 64-bit.

Any ideas?

**Comment by mdreizin** [comment]
@cowwoc webpack.compile accepts only `webpack.config.js` files and tries to compile them.

**Comment by cowwoc** [comment]
@mdreizin 

> `webpack.compile()` only accepts `webpack.config.js` files and tries to compile them.

1. In all the examples I've seen you post you pass the **contents** of the config file inline (as opposed to the path of the `webpack.config.js` file). Which is it?
2. If I'm using the API wrong, shouldn't I get an error message?
3. I am already using `gulp.dest()` as you can see in the above code snippet. Do you have a sample project for `gulp-webpack-build` that I could base a minimal testcase on?

**Comment by cowwoc** [comment]
Ahhh! The API documentation helps a lot!

Okay, here's what's going on:

`gulp.src(config.srcDir + "**/*.js")` is returning the entry point JS files. It does not contain `webpack.config.js`.

I'd like to propose the following changes:
1. The example on README.md should state explicitly that users are expected to pass the webpack configuration file as part of `gulp.src()` or inline to `compile()` (the latter overrides the former). Right now it's not obvious at all that `gulp.src()` is meant to contain the configuration file (in my case, it only contained the entry point Javascript files).
2. The library should throw an error on an empty configuration (meaning, `gulp.src()` does not contain `webpack.config.js` and `compile()` is passed an `undefined`, `null` or empty object.

**Comment by cowwoc** [comment]
@mdreizin I dug into the source-code and identified the following problems:

1. `gulp.src()` expects to take in one or more `webpack.config.js` files, not entry-point Javascript files. Please document this fact.
2. https://github.com/mdreizin/gulp-webpack-build/blob/master/lib/compiler.js#L26 requires the configuration file to contain `gulp: true`, a fact that doesn't seem to be documented anywhere. Why is this even needed? Can it be removed? If not, please document it.
3. If the library doesn't find any matching configuration files, it fails silently. Please have it throw an error instead.

When I run:

```
	return gulp.src("./gulp/webpack.config.js").
		pipe(webpack.compile()).
		pipe(webpack.format(
		{
			version: false,
			timings: true
		})).
		pipe(webpack.failAfter(
		{
			errors: true,
			warnings: true
		})).
		pipe(gulp.dest(config.targetDir + "com/realestate/frontend/page")).
		pipe(reload({stream: true}));
```

I now get:

```
[18:00:32] Compiling webpack config ~\Documents\realestate\frontend\gulp\webpack.config.js
[18:00:32]
Time: 3203ms
                                            Asset     Size  Chunks             Chunk Names
images/flags.4b38521e79b5ccd1a1e9ab02d0998cef.png   145781          [emitted]
images/icons.e295131b497384be19fec6dfe154d6b1.svg   253486          [emitted]
fonts/icons.fdf491ce5ff5b2da02708cd0e9864719.woff    83760          [emitted]
 fonts/icons.4f0022f25672c7f501c339cbf98d9117.ttf   141564          [emitted]
 fonts/icons.90186830c9c50a0fed932494581761d9.eot    72449          [emitted]
                                         Index.js   131101       0  [emitted]  Index
                                         Users.js  1278463       1  [emitted]  Users
                               Authentications.js   732622       2  [emitted]  Authentications
                                    Properties.js  1282631       3  [emitted]  Properties
                                        Common.js   837271       4  [emitted]  Common.js

ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' d:\Users\Gili\Documents\realestate\frontend\node_modules\webpack\node_modules\node-libs-browser\node_modules\process\browser.js/browser.js in d:\Users\Gili\Documents\realestate\frontend\node_modules\webpack\node_modules\node-libs-browser\node_modules\timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-webpack-build\index.js:170:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-webpack-build\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:96
5:16
    at process._tickCallback (node.js:442:13)
```

It's not clear why I'm getting this exception. I don't get this error when using `gulp-webpack` so I'm skeptical that there is anything wrong with my configuration.

**Comment by mdreizin** [comment]
@cowwoc you will get the same error if you will try native `webpack` compiler via `webpack --config webpack.config.js`.

I'm using native `webpack` compiler and just load `webpack.config.js` via `webpack-config` lib and then pass this config to `webpack.run` or `webpack.watch`.

The main difference is that `gulp-webpack` uses `entry` via `gulp.src` and you should use the one config for each entries, instead of that my implementation works the same as `webpack --config webpack.config.js` and it gives you more flexibility to use `webpack.config.js`.

If you look at [gulp-webpack/index.js:99](https://github.com/shama/gulp-webpack/blob/master/index.js#L99) you can see that `webpack` throws `err` when it can't bundle (has fatal error) and here there is no logic to work with `[stats](http://webpack.github.io/docs/node.js-api.html#stats)` object, but `stats` may contain some errors and warnings. `gulp-webpack` just ignore them and that is why you dont see any erros or warnings, but you should see them, because your bundle is not successfully compiled.

I can help you with pleasure, but I don't see your `webpack.config.js`.

**Comment by cowwoc** [comment]
Sorry for the delay. It took me a long time to produce a minimal testcase.

The error message I am getting seems to be a problem in webpack, not this gulp plugin, so I filed https://github.com/webpack/webpack/issues/747

For the purpose of **this** bug report, can you please fix points 1, 2, 3 mentioned at https://github.com/mdreizin/gulp-webpack-build/issues/2#issuecomment-72286131?

**Comment by mdreizin** [comment]
@cowwoc 1. Done. 2. I will fix it. 3. Please see https://github.com/mdreizin/gulp-webpack-build/blob/master/samples/gulpfile.js

**Comment by cowwoc** [comment]
@mdreizin Sorry, how does https://github.com/mdreizin/gulp-webpack-build/blob/master/samples/gulpfile.js address the fact that the plugin should throw an error if no configuration file is found (point 3)?

**Comment by mdreizin** [comment]
@cowwoc 3. It has not been implemented yet.

**Comment by cowwoc** [comment]
Sounds good. I'll keep my eye open for these changes.

**Comment by mdreizin** [comment]
@cowwoc

2. Has been implemented, please update to v0.2.7.
3. I thought about it and unfortunately it would not be implemented.

**Comment by mdreizin** [comment]
@cowwoc Please update to v0.2.9

**Comment by cowwoc** [comment]
@mdreizin I think this issue needs to be reopened. v0.2.9 does not throw an error if no configuration file is found (e.g. `gulp.src()` points to a non-existent or non-configuration file). It fails silently.

By comparison, invoking Webpack directly fails with:

```
Error: Cannot find module 'C:\Users\Gili\Documents\realestate\frontend\webpack.config.js'
```

I understand that `gulp.src()` sends you nothing for non-existent files, but you can check for that condition by checking if your plugin receives no files (or none of the files you are sent are  configuration files).
