### ISSUE TITLE
gulp.dest() resolving relative to output.path

### ISSUE THREAD

**Issue by cowwoc** [mdreizin/gulp-webpack-build#6]
When using `gulp.dest()` with this plugin, I am finding that relative paths resolve relative to webpack's `output.path` as opposed to the path of the enclosing `Gulpfile.js` as I was expecting. No other gulp plugin I've seen behaves like this.

Is this by design? Or a bug?

**Comment by mdreizin** [comment]
@cowwoc it is by design and you should not specify `output.path`, instead of that you should use `gulp.dest`. It is necessary to properly resolve the path passed in `gulp.dest`.

**Comment by mdreizin** [comment]
@cowwoc please look at:

https://github.com/mdreizin/gulp-webpack-build/blob/master/index.js#L53
https://github.com/mdreizin/gulp-webpack-build/blob/master/lib/compiler.js#L120

**Comment by cowwoc** [comment]
@mdreizin I suggest reconsidering this design because you're asking users to choose between being able to run from Webpack CLI or gulp-webpack-build but not both.

If you remove the `join()` then users should be able to share the same configuration file across both modes.

**Comment by cowwoc** [comment]
@mdreizin I saw your recent commits. I posted a bunch of comments/questions to https://github.com/mdreizin/gulp-webpack-build/commit/ab3f124b5774172f6b56644adac5923873464dde.
