### ISSUE TITLE
watch() not writing any files

### ISSUE THREAD

**Issue by cowwoc** [mdreizin/gulp-webpack-build#7]
`gulp.watch()` is invoking this method on "change":

```
	console.log("*** webpack.watch: " + event.path);
	webpack.watch(event.path, webpackOptions,
	{
		base: path.resolve(event.path)
	}, function(err, stats)
	{
		console.log("*** webpack.proxy: " + event.path + ", err: " + toJson(err) + ", stats: " + toJson(stats));
		gulp.src(event.path).
			pipe(webpack.proxy(err, stats)).
			pipe(webpack.format(
			{
				version: false
			})).
			pipe(gulp.dest(".")).
			pipe(reload({stream: true}));
	});
```

I am getting this output:

```
*** webpack.watch: C:\Users\Gili\Documents\realestate\frontend\src\main\webapp\com\realestate\frontend\page\Index.scss
[18:51:46] Watching webpack config ~\Documents\realestate\frontend\webpack.config.js
*** webpack.proxy: C:\Users\Gili\Documents\realestate\frontend\src\main\webapp\com\realestate\frontend\page\Index.scss, err: null, stats: 
{
  "compilation": ...,
  "hash": "7c392354865954de5f01",
  "startTime": 1423093906078,
  "endTime": 1423093906855
}
[18:51:46] Compiling webpack config ~\Documents\realestate\frontend\webpack.config.js
[18:51:46] 
              Asset    Size  Chunks             Chunk Names
      Properties.js   30371       0  [emitted]  Properties
 Authentications.js    8661       1  [emitted]  Authentications
           Index.js    2191       2  [emitted]  Index
           Users.js   12341       3  [emitted]  Users
          Common.js  131123       4  [emitted]  Common
Authentications.css     449       1  [emitted]  Authentications
          Index.css     632       2  [emitted]  Index
         Common.css     190       4  [emitted]  Common
Child extract-text-webpack-plugin:
    
Child extract-text-webpack-plugin:
    
Child extract-text-webpack-plugin:
    
[BS] 8 files changed (Properties.js, Authentications.js, Index.js, Users.js, Common.js, Authentications.css, Index.css, Common.css)
*** webpack.proxy: C:\Users\Gili\Documents\realestate\frontend\src\main\webapp\com\realestate\frontend\page\Index.scss, err: null, stats: 
{
  "compilation": ...,
  "hash": "7c392354865954de5f01",
  "startTime": 1423093907182,
  "endTime": 1423093907231
}
[18:51:47] Starting 'csslint'...
[18:51:47] Compiling webpack config ~\Documents\realestate\frontend\webpack.config.js
[18:51:47] 
              Asset  Size  Chunks             Chunk Names
Authentications.css   449       1  [emitted]  Authentications
          Index.css   632       2  [emitted]  Index
         Common.css   190       4  [emitted]  Common
[18:51:47] Finished 'csslint' after 20 ms
[18:51:47] Starting 'css'...
[18:51:47] Finished 'css' after 7.02 Î¼s
[BS] 3 files changed (Authentications.css, Index.css, Common.css)
```

Some observations:
1. `webpack.watch()` is being invoked once (which is correct) but `webpack.proxy()` is being invoked twice for the same file (which is incorrect). Why is that? As you can see `stats.hash` is the same.
2. `[BS] 3 files changed (Authentications.css, Index.css, Common.css)` is printed by `pipe(reload({stream: true}))` (BS stands for http://www.browsersync.io/) indicating that webpack modified those 3 files but when I check the files are never actually written to disk.
3. In https://github.com/mdreizin/gulp-webpack-build/issues/2#issuecomment-72286131 I discovered that for non-watch builds `gulp.src()` is supposed to take in `webpack.config.js`. I am a little surprised to see that `webpack.watch()` does not take in `webpack.config.js` but instead takes in a configuration object (the contents of `webpack.config.js`). Is this a bug in my script? Should I be feeding in `webpack.config.js` anywhere?
4. I am modifying `Index.scss` and expecting webpack to output `Index.css`. Instead, it seems to be re-running the full build (outputting Javascript files in the process). How do I get it to only overwrite the modified CSS file?

Thanks...

**Comment by cowwoc** [comment]
Repro steps:

1. Clone https://github.com/cowwoc/gulp-webpack-build-issue7
2. `npm install` in the root directory
3. Run `gulp build` and confirm that `target/classes/Index.js` is created containing `var version = 9;`
4. Run `gulp watch`
5. Edit `src/main/webapp/Index.js`, set `version = 10`, save file.
6. Open `target/classes/Index.js`, confirm that it still contains `var version = 9;`
7. To prove that nothing is being written, delete `target/classes/Index.js`, update `src/main/webapp/Index.js` again and notice that `target/classes/Index.js` is not recreated.

**Comment by mdreizin** [comment]
Hello @cowwoc

1. It is correct, because `webpack` Node.js API calls `callback` twice first time, the next time it will be called once.
Please see [the documentation](http://webpack.github.io/docs/node.js-api.html#the-long-way): `Note: watch will automatically run an initial build, so you should either call run or watch.`
2. It is configuration issue. Currently you should use`gulp.dest('target/classes')`(without defining `ouput.path` in `webpack.config.js`) instead of `gulp.dest(.)`. Also some comments about #6 I will add soon.
3. Please see [API documentation](https://github.com/mdreizin/gulp-webpack-build/blob/master/docs/API.md#webpackwatchfilename-options-globoptions-callback).
4. It is not possible, because `webpack` overwrites files automatically. Please see [gulp incremental builds](https://github.com/gulpjs/gulp#incremental-builds).

**Comment by cowwoc** [comment]
@mdreizin I tried what you wrote (`gulp.dest('target/classes')` without defining `output.path` in `webpack.config.js`) but still no files were written out.

Did you test this against https://github.com/cowwoc/gulp-webpack-build-issue7? If you are able to get it to work on your end (preferably under Windows, since this could be an OS-specific bug), can you please fork and commit your changes so I can try the fixed configuration on my end?

Thanks.

**Comment by mdreizin** [comment]
@cowwoc Please wait a little bit I have found proper solution and I'm working on it.

**Comment by cowwoc** [comment]
@mdreizin Sounds good. Let me know when you've got something for me to test. Thanks!

**Comment by cowwoc** [comment]
@mdreizin I saw your recent commits. I posted a bunch of comments/questions to https://github.com/mdreizin/gulp-webpack-build/commit/ab3f124b5774172f6b56644adac5923873464dde.

**Comment by cowwoc** [comment]
I believe you fixed all the problems reported by this issue. Feel free to mark it as closed.
