### ISSUE TITLE
Problems piping output from watch()

### ISSUE THREAD

**Issue by cowwoc** [mdreizin/gulp-webpack-build#8]
Version 0.3.0

Given:

```
var browserSync = require("browser-sync");
var reload = browserSync.reload;

function fileChanged(event)
{
	gulp.src("./webpack.config.js").
		pipe(webpack.watch(event.path,
		{
			useMemoryFs: true
		}, function(stream, err, stats)
		{
			gulp.src(event.path).
				pipe(webpack.proxy(err, stats)).
				pipe(webpack.format(
				{
					version: false
				})).
				// Resolves relative to webpack.config.js:output.path
				pipe(gulp.dest(".")).
				pipe(reload({stream: true}));
		}));
}

gulp.task("browser-sync", function()
{
	browserSync(
	{
		proxy: "http://localhost:8080/",
		notify: false
	});
});

gulp.task("watch", ["browser-sync"], function()
{
	gulp.watch(buildConfig.srcDir + "**/*.js", ["javascript"]).on("change", fileChanged);
});
```

I am expecting `pipe(reload({stream: true}));` to get passed the modified files. Instead, I am seeing webpack.watch() updates files on disk (good!) but `pipe(reload({stream: true}));` never gets invoked (or maybe it's getting passed an empty list).

Can you reproduce this on your end?

(This used to work in 0.2.8)

**Comment by mdreizin** [comment]
@cowwoc As I understand `Index.js` should exist at `target/classes` directory. Correct?

**Comment by cowwoc** [comment]
Yes, the file is being written but browser-sync is not getting notified. Meaning, I am forced to refresh the browser manually (hitting F5) as opposed to having browser-sync do this for me (yeah, I'm lazy :)).

**Comment by mdreizin** [comment]
@cowwoc Please see https://github.com/mdreizin/gulp-webpack-build-issue7/tree/3f3a0c34980a25ec88d1715efcdcb6a6a15c1c9a

**Comment by mdreizin** [comment]
@cowwoc Currently it is not working with `useMemoryFs`. I will fix that.

**Comment by cowwoc** [comment]
@mdreizin FYI: I just tested with `useMemoryFs = false`. `browser-sync` is still not notified.

**Comment by mdreizin** [comment]
@cowwoc Please see the updates https://github.com/mdreizin/gulp-webpack-build-issue7/commit/e282b22a61952186b6b09230a753769996521159.

**Comment by cowwoc** [comment]
@mdreizin It took me forever to notice the problem in my code. It turns out that I was invoking: `webpack.watch(event.path, webpackOptions,  function(stream, err, stats) { ... })`. That first argument is wrong. Any chance you could throw an error if the first argument of `webpack.watch()` is a non-object?

Also, the documentation for `stream` is very vague. I had no idea that you could `pipe()` on it instead of invoking `gulp.src(event.path)` inside the callback. This stream is very useful. Is there any way you could improve the documentation here? Perhaps use `stream` in the sample code and have the documentation point to that sample?

**Comment by mdreizin** [comment]
@cowwoc I will update the documentation.
